trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Instala o JDK 21 manualmente
- script: |
    sudo apt update
    sudo apt install -y openjdk-21-jdk
    echo "JAVA_HOME set to /usr/lib/jvm/java-21-openjdk-amd64"
  displayName: 'Install JDK 21'

# Configura o Maven para compilar o projeto usando o JDK instalado
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkUserInputPath: '/usr/lib/jvm/java-21-openjdk-amd64' # Caminho manual para o JDK
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
