trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '21'  # Definindo a versão do JDK para 21
    jdkArchitectureOption: 'x64'  # Arquitetura do JDK (x64 é o mais comum)
    jdkPackageType: 'JDK'
    installationPath: $(Agent.ToolsDirectory)/jdk-21
    jdkSourceOption: 'InstallFromMaven'  # Especificando a origem do JDK (Maven)

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '21'  # Especificando a versão correta do JDK
    jdkArchitectureOption: 'x64'  # Especificando a arquitetura correta
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
